var sentences = [
"Knowing that your [noun-neutral] are [adj-bad] and [adv] [adj-bad], we ask — how is continued [noun-bad] against [adj-marginalized] lives not enough [noun-neutral] of a [adj-neutral] need for [noun-neutral]? This begs the question[punc] Will the [noun-neutral] granted with [noun-neutral] [noun-neutral] extend as long as [noun-bad] exists? As long as Tufts is [adj-bad]?",
"By forcing [noun-neutral] into this [noun-bad][punc] you [adverb] keep many from [gerund] and are [adverb] [gerund] that this [noun-neutral], [noun-bad] and [noun-bad] in the existing [adj-bad] [noun-neutral] will go on [adj-neutral].",
"Rather, these [noun-neutral] are [adv] about [noun-neutral] of [noun-neutral] on [noun-neutral], to [verb-good] the [adj-neutral] [noun-bad] and [noun-bad] being done to [noun-good]s both at Tufts and [adv]. He emphasized that to remain [adj-bad] about this [noun-bad] is to be [adj-bad] in it.",
"One of my major regrets vis-a-vis my time spent at Tufts is that I was [adv] [adj-bad] in the [noun-neutral] of the [adj-bad] [noun-bad].",
"As far as [noun-neutral], [noun-neutral], [noun-good] and [adj-good] [noun-good] go, there is no greater [noun-bad] than such [adj-bad] [noun-bad]. [adj-good] [noun-neutral] is the [noun-neutral] of [noun-neutral]. It is the [noun-good] of [adj-neutral] [noun-neutral] and [noun-neutral].",
"The [adj-neutral] status quo wishes to [verb-bad] and [verb-bad] the [noun-neutral]s of campus debate [adv], and through [noun-bad], [noun-bad] and [noun-bad], attempt to [verb-bad] necessary [noun-neutral] and [noun-neutral] by [gerund] a [adj-bad] [noun-neutral] between [adj-good] and [adj-good] [noun-neutral].",
"While discussing an essay that addressed the intersections between [noun-bad], the [adj-bad] complex, and [adj-good] degradation[punc] some students said they felt [adv] offended by the [noun-neutral] because it said that “all men” were responsible for perpetuating not only the [adj-bad] complex, but also the degradation of [noun-good] and the [noun-good].",
"It was not until [adv] [adv] that I could [verb] all the [noun-neutral]s[punc] much of my ‘[noun-neutral]’ as a human comes from [gerund] [noun-neutral]s that are either [adv] or [adv] gendered as [adj-bad].",
"I have seen—and participated in—the pursuit of [noun-bad] and [noun-neutral] [verb-bad] with [adj-bad] notions of [noun-neutral]."
];
