var vocab = {
    "noun" : {
        "good" : [
            "matriarchy",
            "hope",
            "trigger warning",
            "protest",
            "action",
            "hunger strike",
            "pressure",
            "freedom",
            "expression",
            "LGBT Community",
            "activist",
            "blackness",
            "black body",
            "drag queen",
            "drag persona",
            "research",
            "learning",
            "threshing floor"
        ],
        "neutral" : [
            "trait",
            "power",
            "implication",
            "text",
            "Tufts",
            "system",
            "policy",
            "invincibility",
            "rule",
            "culture",
            "leeway",
            "students",
            "final exam",
            "action",
            "disruption",
            "normalcy",
            "campus",
            "argumentation",
            "disputation",
            "debate",
            "essence",
            "opinion",
            "conviction",
            "parameter",
            "determination",
            "controversy",
            "argumentation",
            "dichotomy"
        ],
        "bad" : [
            "patriarchy",
            "racism",
            "ignorance",
            "complicity",
            "patriarchy",
            "cisheteropatriarchy",
            "cis-het scum",
            "greek life",
            "frat",
            "toughness",
            "rage",
            "anti-blackness",
            "whiteness",
            "injustice",
            "violence",
            "radical",
            "republican",
            "complicity",
            "silence",
            "oppression",
            "status quo",
            "fallacy",
            "vomit",
            "distraction",
            "tautology",
            "redefinition"
        ]
    },
    "adj" : {
        "good" : [
            "socialist",
            "progressive",
            "Bernie-supporting",
            "environmental",
            "LGBT",
            "marginalized",
            "diverse",
            "feminine",
            "multicultural",
            "open",
            "liberal",
            "genuine",
            "polemical",
            "academic"
        ],
        "neutral" : [
            "postmodern",
            "neopostmodern",
            "systematic",
            "systemic",
            "student",
            "mild",
            "powerful",
            "immense",
            "on-campus",
            "nationwide",
            "androgynous",
            "androsexual",
            "drag",
            "personal",
            "entrenched"
        ],
        "bad" : [
            "damaging",
            "Trump-supporting",
            "regressive",
            "military-industrial",
            "racist",
            "classist",
            "homophobic",
            "transphobic",
            "queerphobic",
            "homotransqueerphobic",
            "oppressive",
            "violent",
            "literally violent",
            "cis",
            "het",
            "cis-het",
            "white",
            "male",
            "republican",
            "conservative",
            "silent",
            "masculine",
            "complicit",
            "apathetic",
            "relativist",
            "false"
        ],
        "marginalized" : [
            "black",
            "queer",
            "feminine",
            "femme",
            "queerfemme",
            "blackfemme",
            "trans",
            "genderqueer",
            "indigenous",
            "female",
            "aboriginal"
        ]
    },
    "verb" : {
        "good" : [
            "parcitipate",
            "unpack",
            "discuss",
            "understand",
            "make progress",
            "indict",
            "fight",
            "highlight"
        ],
        "neutral" : [
            "participate",
            "exhibit",
            "express",
            "turn",
            "shatter"
        ],
        "bad" : [
            "blur",
            "regress",
            "silence",
            "complicitize",
            "appropriate",
            "monopolize",
            "subvert"
        ]
    },
    "punc" : [
            ";",
            ":",
            ",",
            "--",
            "..."
    ],
    "gerund" : [
        "genderizing",
        "expressing",
        "exhibiting",
        "protesting",
        "oppressing",
        "attempting",
        "deracializing",
        "presenting"
    ],
    "adv" : [
        "explicitly",
        "implicitly",
        "complicitly",
        "thus",
        "thusly",
        "racially",
        "marginally",
        "obscenely",
        "literally",
        "immensely",
        "fundamentally",
        "globally",
        "unwittingly",
        "accordingly"
    ]
};
